export const BANNER_LIST_REQUEST = 'BANNER_LIST_REQUEST'
export const BANNER_LIST_SUCCESS = 'BANNER_LIST_SUCCESS'
export const BANNER_LIST_FAILED = 'BANNER_LIST_FAILED'

export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST'
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS'
export const BRAND_LIST_FAILED = 'BRAND_LIST_FAILED'

export const BRAND_SAVE_REQUEST = 'BRAND_SAVE_REQUEST'
export const BRAND_SAVE_SUCCESS = 'BRAND_SAVE_SUCCESS'
export const BRAND_SAVE_FAILED = 'BRAND_SAVE_FAILED'

export const BRAND_DELETE_REQUEST = 'BRAND_DELETE_REQUEST'
export const BRAND_DELETE_SUCCESS = 'BRAND_DELETE_SUCCESS'
export const BRAND_DELETE_FAILED = 'BRAND_DELETE_FAILED'

export const CAT_LIST_REQUEST = 'CAT_LIST_REQUEST'
export const CAT_LIST_SUCCESS = 'CAT_LIST_SUCCESS'
export const CAT_LIST_FAILED = 'CAT_LIST_FAILED'

export const CAT_SAVE_REQUEST = 'CAT_SAVE_REQUEST'
export const CAT_SAVE_SUCCESS = 'CAT_SAVE_SUCCESS'
export const CAT_SAVE_FAILED = 'CAT_SAVE_FAILED'

export const CAT_DELETE_REQUEST = 'CAT_DELETE_REQUEST'
export const CAT_DELETE_SUCCESS = 'CAT_DELETE_SUCCESS'
export const CAT_DELETE_FAILED = 'CAT_DELETE_FAILED'
